# Generated by Django 2.2.1 on 2019-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doughnut_fruit_waffle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('date_f', models.DateTimeField()),
                ('date_s', models.DateTimeField()),
            ],
        ),
    ]
