# Generated by Django 2.2.1 on 2019-06-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_f',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_s',
            field=models.DateField(),
        ),
    ]
