# Generated by Django 2.2.1 on 2019-06-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190616_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_f',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_s',
            field=models.DateField(),
        ),
    ]
